// import './globals.css'
import Footer from './component/Footer';
import Header from './component/Header';
export const metadata = {
  title: 'My Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa:IR">
      <body>
        <div className="flex flex-col  min-h-screen justify-between">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
